### PR TITLE
submit: MediaPlayer

### PR DESCRIPTION
**Pull request by WillowSauceR**

### CODE REVIEW

**Comment by RimuruChan** [comment]
Other hook library may conflict with LiteLoaderBDS's hook library. Please use PreLoader(ll2) 's C API instead of current one.

What's more, the plugin has too little feature and low customize ability. It is even not suitable for productive environment.

Please reopen an PR after you fix it.

**Review by RimuruChan — CHANGES_REQUESTED** [review]
Other hook library may conflict with LiteLoaderBDS's hook library. Please use PreLoader(ll2) 's C API instead of current one.

What's more, the plugin has too little feature and low customize ability. It is even not suitable for productive environment.

Please request a review after you fix it.

**Comment by WillowSauceR** [comment]
> Other hook library may conflict with LiteLoaderBDS's hook library. Please use PreLoader(ll2)'s C API instead of current one.
> 
> What's more, the plugin has too little feature and low customize ability. It is even not suitable for productive environment.
> 
> Please reopen a PR after you fix it.

First, the plugin does not depend on LiteLoaderBDS, which means that LiteLoaderBDS is not necessary for the plugin to work.
Second, long-term testing has shown that MinHook is compatible with Detour, which means that the incompatibility issue is nonsense.
Further, I have indicated in the README that the plugin is in the early stages of development and is currently a demo version. It is normal to have few features, and I will gradually add new features through updates in the next few days

Code is being written to read nbs music data
image



*If you have not tested my code and plugin, then you should not feel free to post comments*

**Comment by RimuruChan** [comment]
## First of all

Lip is a generic package manager, which **DOES NOT** mean you can submit **ANYTHING** in Lip's registry, although we are planning to change the name to LLPI.

## Second

Lip is designed for LiteLoaderBDS only, and is influenced by its requirements and features to support just such a "generic", not generic for generic's sake.

## Thrid

I tested your plug-in on Windows Sandbox and your plugin works fine, but there is a potential risk of conflict, as normally a program should not use both hook frameworks such as Detours and minhook, and LLBDS's PreLoader maintains its own call chain of hook.

## Last

As I mentioned, your plugin is not functional enough and needs to be further enhanced with customization features, although others have already implemented them. [LLSE-NBSPlayer](https://www.minebbs.com/resources/nbsplayer-bds-nbs.4479/)

**Pull request closed without merging**
